/**
 * Zod schemas for Contacts service
 *
 * These schemas will be used to validate incoming RPC requests
 *
 * Generated file - do not edit manually
 */

import { z } from "zod";

// Generated by ts-to-zod from interfaces.ts

export const ContactSchema = z.object({
  id: z.string(),
  firstName: z.string(),
  lastName: z.string(),
  username: z.string(),
  email: z.string(),
  phone: z.string(),
  favorite: z.boolean(),
  avatar: z.string().optional(),
});

export const NewContactSchema = z.object({
  firstName: z.string(),
  lastName: z.string(),
  username: z.string(),
  email: z.string(),
  phone: z.string(),
  avatar: z.string().optional(),
});

// function parameter schemas

export const fetchContactByIdSchema = z.object({
  id: z.string(),
});

export const createContactSchema = z.object({
  contact: NewContactSchema,
});

export const deleteContactSchema = z.object({
  id: z.string(),
});

export const updateFavoriteStatusSchema = z.object({
  id: z.string(),
  favorite: z.boolean(),
});
